version: 2.1

orbs:
  vulnachecka: whitesource/whitesource-scan@19.12.1

workflows:
  test:
    jobs:
    - vulnachecka/scan:
        config_file_path:  "wss-unified-agent.config"
        commands_file_path: "install_commands.sh" 
